[[headers]]
  for = "/assets/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.mjs"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.ts"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.jsx"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.tsx"
    [headers.values]
    Content-Type = "application/javascript"

# Handle single page application routing
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build settings
[build]
  publish = "dist"
  command = "npm run build"